"use client";

import React, { useState, useEffect } from 'react';
import { Calendar, Clock, User, Plus, FileText, CheckCircle, X, Download, Search, Filter, ArrowUpDown } from 'lucide-react';
import { useToast } from '@/components/ui/Toast';
import { LoadingSpinner, CardSkeleton } from '@/components/ui/LoadingSpinner';

interface User {
  id: number;
  username: string;
  displayName: string;
}

interface OneOnOneMeeting {
  id: number;
  employeeId: number;
  managerId: number;
  scheduledAt: string;
  status: 'SCHEDULED' | 'COMPLETED' | 'CANCELLED';
  autoGeneratedAgenda: string | null;
  customAgenda: string | null;
  discussionTopics: string | null;
  actionItems: string | null;
  notes: string | null;
  employee?: User;
  manager?: User;
}

interface MeetingFormData {
  employeeId: number;
  managerId: number;
  scheduledAt: string;
  customAgenda?: string;
}

export default function OneOnOneMeetingsPage() {
  const toast = useToast();
  const [meetings, setMeetings] = useState<OneOnOneMeeting[]>([]);
  const [filteredMeetings, setFilteredMeetings] = useState<OneOnOneMeeting[]>([]);
  const [upcomingMeetings, setUpcomingMeetings] = useState<OneOnOneMeeting[]>([]);
  const [users, setUsers] = useState<User[]>([]);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [showCreateForm, setShowCreateForm] = useState(false);
  const [selectedMeeting, setSelectedMeeting] = useState<OneOnOneMeeting | null>(null);
  const [viewMode, setViewMode] = useState<'upcoming' | 'all' | 'as-employee' | 'as-manager'>('upcoming');

  // フィルター・検索・並び替えの状態
  const [searchQuery, setSearchQuery] = useState('');
  const [statusFilter, setStatusFilter] = useState<'ALL' | 'SCHEDULED' | 'COMPLETED' | 'CANCELLED'>('ALL');
  const [sortBy, setSortBy] = useState<'date' | 'status'>('date');
  const [sortOrder, setSortOrder] = useState<'asc' | 'desc'>('desc');

  // フォーム状態
  const [formData, setFormData] = useState<MeetingFormData>({
    employeeId: 0,
    managerId: 0,
    scheduledAt: '',
    customAgenda: '',
  });

  // ミーティング編集用の状態
  const [editingMeeting, setEditingMeeting] = useState<Partial<OneOnOneMeeting> | null>(null);

  useEffect(() => {
    fetchMeetings();
    fetchUsers();
  }, [viewMode]);

  // フィルター・検索・並び替え処理
  useEffect(() => {
    let result = [...meetings];

    // ステータスフィルター
    if (statusFilter !== 'ALL') {
      result = result.filter(meeting => meeting.status === statusFilter);
    }

    // 検索フィルター
    if (searchQuery.trim()) {
      result = result.filter(meeting => {
        const query = searchQuery.toLowerCase();
        return (
          meeting.employee?.displayName?.toLowerCase().includes(query) ||
          meeting.manager?.displayName?.toLowerCase().includes(query) ||
          meeting.customAgenda?.toLowerCase().includes(query) ||
          meeting.autoGeneratedAgenda?.toLowerCase().includes(query)
        );
      });
    }

    // 並び替え
    result.sort((a, b) => {
      if (sortBy === 'date') {
        const dateA = new Date(a.scheduledAt).getTime();
        const dateB = new Date(b.scheduledAt).getTime();
        return sortOrder === 'asc' ? dateA - dateB : dateB - dateA;
      } else {
        // status順
        const statusOrder = { SCHEDULED: 1, COMPLETED: 2, CANCELLED: 3 };
        const orderA = statusOrder[a.status];
        const orderB = statusOrder[b.status];
        return sortOrder === 'asc' ? orderA - orderB : orderB - orderA;
      }
    });

    setFilteredMeetings(result);
  }, [meetings, searchQuery, statusFilter, sortBy, sortOrder]);

  const fetchMeetings = async () => {
    setLoading(true);
    try {
      let endpoint = '';
      switch (viewMode) {
        case 'upcoming':
          endpoint = '/api/one-on-one/upcoming';
          break;
        case 'as-employee':
          endpoint = '/api/one-on-one/as-employee';
          break;
        case 'as-manager':
          endpoint = '/api/one-on-one/as-manager';
          break;
        default:
          endpoint = '/api/one-on-one/as-employee'; // デフォルトは従業員として
      }

      const response = await fetch(endpoint, {
        headers: {
          'Authorization': `Bearer ${localStorage.getItem('token')}`,
        },
      });

      if (response.ok) {
        const data = await response.json();
        if (viewMode === 'upcoming') {
          setUpcomingMeetings(data);
        } else {
          setMeetings(data);
        }
      } else {
        toast.error('ミーティング情報の取得に失敗しました');
      }
    } catch (error) {
      console.error('Failed to fetch meetings:', error);
      toast.error('ミーティング情報の取得中にエラーが発生しました');
    } finally {
      setLoading(false);
    }
  };

  const fetchUsers = async () => {
    try {
      const response = await fetch('/api/users', {
        headers: {
          'Authorization': `Bearer ${localStorage.getItem('token')}`,
        },
      });

      if (response.ok) {
        const data = await response.json();
        setUsers(data);
      }
    } catch (error) {
      console.error('Failed to fetch users:', error);
    }
  };

  const handleCreateMeeting = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      setSaving(true);
      toast.info('ミーティングを作成中...');

      const response = await fetch('/api/one-on-one', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${localStorage.getItem('token')}`,
        },
        body: JSON.stringify(formData),
      });

      if (response.ok) {
        const newMeeting = await response.json();
        setMeetings([...meetings, newMeeting]);
        setShowCreateForm(false);
        resetForm();
        fetchMeetings();
        toast.success('ミーティングを作成しました');
      } else {
        const errorData = await response.json().catch(() => null);
        toast.error(errorData?.message || 'ミーティングの作成に失敗しました');
      }
    } catch (error) {
      console.error('Failed to create meeting:', error);
      toast.error('ミーティング作成中にエラーが発生しました');
    } finally {
      setSaving(false);
    }
  };

  const handleUpdateMeeting = async (meetingId: number) => {
    if (!editingMeeting) return;

    try {
      setSaving(true);
      toast.info('ミーティング情報を更新中...');

      const response = await fetch(`/api/one-on-one/${meetingId}`, {
        method: 'PUT',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${localStorage.getItem('token')}`,
        },
        body: JSON.stringify(editingMeeting),
      });

      if (response.ok) {
        fetchMeetings();
        setEditingMeeting(null);
        setSelectedMeeting(null);
        toast.success('ミーティング情報を更新しました');
      } else {
        const errorData = await response.json().catch(() => null);
        toast.error(errorData?.message || 'ミーティングの更新に失敗しました');
      }
    } catch (error) {
      console.error('Failed to update meeting:', error);
      toast.error('ミーティング更新中にエラーが発生しました');
    } finally {
      setSaving(false);
    }
  };

  const handleCompleteMeeting = async (meetingId: number) => {
    try {
      toast.info('ミーティングを完了中...');

      const response = await fetch(`/api/one-on-one/${meetingId}/complete`, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${localStorage.getItem('token')}`,
        },
      });

      if (response.ok) {
        fetchMeetings();
        toast.success('ミーティングを完了しました');
      } else {
        toast.error('ミーティングの完了処理に失敗しました');
      }
    } catch (error) {
      console.error('Failed to complete meeting:', error);
      toast.error('ミーティング完了処理中にエラーが発生しました');
    }
  };

  const resetForm = () => {
    setFormData({
      employeeId: 0,
      managerId: 0,
      scheduledAt: '',
      customAgenda: '',
    });
  };

  const formatDate = (dateString: string) => {
    const date = new Date(dateString);
    return date.toLocaleString('ja-JP', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'SCHEDULED':
        return 'bg-blue-100 text-blue-800';
      case 'COMPLETED':
        return 'bg-green-100 text-green-800';
      case 'CANCELLED':
        return 'bg-gray-100 text-gray-800';
      default:
        return 'bg-gray-100 text-gray-800';
    }
  };

  const getStatusText = (status: string) => {
    switch (status) {
      case 'SCHEDULED':
        return '予定';
      case 'COMPLETED':
        return '完了';
      case 'CANCELLED':
        return 'キャンセル';
      default:
        return status;
    }
  };

  const handleExport = async (format: 'csv' | 'excel') => {
    try {
      const response = await fetch(`/api/export/meetings/${format}`, {
        headers: {
          'Authorization': `Bearer ${localStorage.getItem('token')}`,
        },
      });

      if (response.ok) {
        const blob = await response.blob();
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `meetings-${new Date().toISOString().split('T')[0]}.${format === 'excel' ? 'xlsx' : 'csv'}`;
        document.body.appendChild(a);
        a.click();
        window.URL.revokeObjectURL(url);
        document.body.removeChild(a);
      } else {
        console.error('Export failed:', response.statusText);
        alert('エクスポートに失敗しました');
      }
    } catch (error) {
      console.error('Failed to export:', error);
      alert('エクスポートに失敗しました');
    }
  };

  return (
    <div className="min-h-screen bg-gray-50 p-6">
      <div className="max-w-7xl mx-auto">
        {/* ヘッダー */}
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-gray-900 mb-2">1on1ミーティング管理</h1>
          <p className="text-gray-600">マネージャーとメンバー間の1on1ミーティングを管理します</p>
        </div>

        {/* ビューモード切り替え */}
        <div className="mb-6 flex gap-2">
          <button
            onClick={() => setViewMode('upcoming')}
            className={`px-4 py-2 rounded-lg ${
              viewMode === 'upcoming'
                ? 'bg-blue-600 text-white'
                : 'bg-white text-gray-700 border border-gray-300'
            }`}
          >
            今後のミーティング
          </button>
          <button
            onClick={() => setViewMode('as-employee')}
            className={`px-4 py-2 rounded-lg ${
              viewMode === 'as-employee'
                ? 'bg-blue-600 text-white'
                : 'bg-white text-gray-700 border border-gray-300'
            }`}
          >
            従業員として
          </button>
          <button
            onClick={() => setViewMode('as-manager')}
            className={`px-4 py-2 rounded-lg ${
              viewMode === 'as-manager'
                ? 'bg-blue-600 text-white'
                : 'bg-white text-gray-700 border border-gray-300'
            }`}
          >
            マネージャーとして
          </button>
          <div className="ml-auto flex gap-2">
            <div className="relative group">
              <button className="px-4 py-2 bg-gray-100 text-gray-700 rounded-lg hover:bg-gray-200 transition-colors flex items-center gap-2">
                <Download className="w-4 h-4" />
                エクスポート
              </button>
              <div className="absolute right-0 mt-2 w-48 bg-white rounded-md shadow-lg hidden group-hover:block z-10">
                <button
                  onClick={() => handleExport('csv')}
                  className="block w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-gray-100"
                >
                  CSV形式
                </button>
                <button
                  onClick={() => handleExport('excel')}
                  className="block w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-gray-100"
                >
                  Excel形式
                </button>
              </div>
            </div>
            <button
              onClick={() => setShowCreateForm(true)}
              className="px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 flex items-center gap-2"
            >
              <Plus className="w-5 h-5" />
              新規ミーティング作成
            </button>
          </div>
        </div>

        {/* 検索・フィルター・並び替えバー */}
        {viewMode !== 'upcoming' && (
          <div className="mb-6 bg-white rounded-lg p-4 shadow">
            <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
              {/* 検索 */}
              <div className="relative">
                <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-5 h-5" />
                <input
                  type="text"
                  placeholder="検索（参加者、アジェンダ）"
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="w-full pl-10 pr-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                />
              </div>

              {/* ステータスフィルター */}
              <div className="relative">
                <Filter className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-5 h-5" />
                <select
                  value={statusFilter}
                  onChange={(e) => setStatusFilter(e.target.value as any)}
                  className="w-full pl-10 pr-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                >
                  <option value="ALL">すべてのステータス</option>
                  <option value="SCHEDULED">予定</option>
                  <option value="COMPLETED">完了</option>
                  <option value="CANCELLED">キャンセル</option>
                </select>
              </div>

              {/* 並び替え基準 */}
              <div className="relative">
                <ArrowUpDown className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-5 h-5" />
                <select
                  value={sortBy}
                  onChange={(e) => setSortBy(e.target.value as any)}
                  className="w-full pl-10 pr-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                >
                  <option value="date">日付順</option>
                  <option value="status">ステータス順</option>
                </select>
              </div>

              {/* 並び替え順序 */}
              <div>
                <select
                  value={sortOrder}
                  onChange={(e) => setSortOrder(e.target.value as any)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                >
                  <option value="desc">降順</option>
                  <option value="asc">昇順</option>
                </select>
              </div>
            </div>

            {/* フィルター結果表示 */}
            <div className="mt-3 text-sm text-gray-600">
              {filteredMeetings.length} 件のミーティング
              {searchQuery && ` （検索: "${searchQuery}"）`}
              {statusFilter !== 'ALL' && ` （ステータス: ${getStatusText(statusFilter)}）`}
            </div>
          </div>
        )}

        {/* ミーティング作成フォーム */}
        {showCreateForm && (
          <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
            <div className="bg-white rounded-lg p-6 max-w-2xl w-full max-h-[90vh] overflow-y-auto">
              <div className="flex justify-between items-center mb-4">
                <h2 className="text-2xl font-bold">新規ミーティング作成</h2>
                <button onClick={() => setShowCreateForm(false)} className="text-gray-500 hover:text-gray-700">
                  <X className="w-6 h-6" />
                </button>
              </div>

              <form onSubmit={handleCreateMeeting} className="space-y-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">
                    従業員
                  </label>
                  <select
                    value={formData.employeeId}
                    onChange={(e) => setFormData({ ...formData, employeeId: parseInt(e.target.value) })}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md"
                    required
                  >
                    <option value={0}>従業員を選択してください</option>
                    {users.map(user => (
                      <option key={user.id} value={user.id}>
                        {user.displayName} ({user.username})
                      </option>
                    ))}
                  </select>
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">
                    マネージャー
                  </label>
                  <select
                    value={formData.managerId}
                    onChange={(e) => setFormData({ ...formData, managerId: parseInt(e.target.value) })}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md"
                    required
                  >
                    <option value={0}>マネージャーを選択してください</option>
                    {users.map(user => (
                      <option key={user.id} value={user.id}>
                        {user.displayName} ({user.username})
                      </option>
                    ))}
                  </select>
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">
                    予定日時
                  </label>
                  <input
                    type="datetime-local"
                    value={formData.scheduledAt}
                    onChange={(e) => setFormData({ ...formData, scheduledAt: e.target.value })}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md"
                    required
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">
                    カスタムアジェンダ（オプション）
                  </label>
                  <textarea
                    value={formData.customAgenda}
                    onChange={(e) => setFormData({ ...formData, customAgenda: e.target.value })}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md"
                    rows={4}
                    placeholder="ミーティングで話したいトピックを入力してください"
                  />
                </div>

                <div className="flex gap-3">
                  <button
                    type="submit"
                    className="flex-1 bg-blue-600 text-white py-2 rounded-md hover:bg-blue-700"
                  >
                    作成
                  </button>
                  <button
                    type="button"
                    onClick={() => setShowCreateForm(false)}
                    className="flex-1 bg-gray-200 text-gray-800 py-2 rounded-md hover:bg-gray-300"
                  >
                    キャンセル
                  </button>
                </div>
              </form>
            </div>
          </div>
        )}

        {/* ミーティング詳細・編集モーダル */}
        {selectedMeeting && (
          <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
            <div className="bg-white rounded-lg p-6 max-w-4xl w-full max-h-[90vh] overflow-y-auto">
              <div className="flex justify-between items-center mb-4">
                <h2 className="text-2xl font-bold">ミーティング詳細</h2>
                <button onClick={() => {
                  setSelectedMeeting(null);
                  setEditingMeeting(null);
                }} className="text-gray-500 hover:text-gray-700">
                  <X className="w-6 h-6" />
                </button>
              </div>

              <div className="space-y-4">
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                      予定日時
                    </label>
                    <div className="flex items-center gap-2 text-gray-900">
                      <Clock className="w-5 h-5" />
                      {formatDate(selectedMeeting.scheduledAt)}
                    </div>
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                      ステータス
                    </label>
                    <span className={`px-3 py-1 rounded-full text-sm ${getStatusColor(selectedMeeting.status)}`}>
                      {getStatusText(selectedMeeting.status)}
                    </span>
                  </div>
                </div>

                {selectedMeeting.autoGeneratedAgenda && (
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                      自動生成アジェンダ
                    </label>
                    <div className="bg-gray-50 p-4 rounded-md whitespace-pre-wrap">
                      {selectedMeeting.autoGeneratedAgenda}
                    </div>
                  </div>
                )}

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">
                    カスタムアジェンダ
                  </label>
                  <textarea
                    value={editingMeeting?.customAgenda ?? selectedMeeting.customAgenda ?? ''}
                    onChange={(e) => setEditingMeeting({ ...editingMeeting, customAgenda: e.target.value })}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md"
                    rows={3}
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">
                    ディスカッショントピック
                  </label>
                  <textarea
                    value={editingMeeting?.discussionTopics ?? selectedMeeting.discussionTopics ?? ''}
                    onChange={(e) => setEditingMeeting({ ...editingMeeting, discussionTopics: e.target.value })}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md"
                    rows={4}
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">
                    アクションアイテム
                  </label>
                  <textarea
                    value={editingMeeting?.actionItems ?? selectedMeeting.actionItems ?? ''}
                    onChange={(e) => setEditingMeeting({ ...editingMeeting, actionItems: e.target.value })}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md"
                    rows={4}
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">
                    メモ
                  </label>
                  <textarea
                    value={editingMeeting?.notes ?? selectedMeeting.notes ?? ''}
                    onChange={(e) => setEditingMeeting({ ...editingMeeting, notes: e.target.value })}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md"
                    rows={4}
                  />
                </div>

                <div className="flex gap-3 pt-4">
                  {selectedMeeting.status === 'SCHEDULED' && (
                    <>
                      <button
                        onClick={() => handleUpdateMeeting(selectedMeeting.id)}
                        className="flex-1 bg-blue-600 text-white py-2 rounded-md hover:bg-blue-700"
                      >
                        保存
                      </button>
                      <button
                        onClick={() => handleCompleteMeeting(selectedMeeting.id)}
                        className="flex-1 bg-green-600 text-white py-2 rounded-md hover:bg-green-700 flex items-center justify-center gap-2"
                      >
                        <CheckCircle className="w-5 h-5" />
                        完了にする
                      </button>
                    </>
                  )}
                  <button
                    onClick={() => {
                      setSelectedMeeting(null);
                      setEditingMeeting(null);
                    }}
                    className="flex-1 bg-gray-200 text-gray-800 py-2 rounded-md hover:bg-gray-300"
                  >
                    閉じる
                  </button>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* ミーティング一覧 */}
        <div className="bg-white rounded-lg shadow">
          {loading ? (
            <div className="p-8 text-center text-gray-500">読み込み中...</div>
          ) : (
            <div className="divide-y divide-gray-200">
              {(viewMode === 'upcoming' ? upcomingMeetings : filteredMeetings).length === 0 ? (
                <div className="p-8 text-center text-gray-500">
                  {searchQuery || statusFilter !== 'ALL'
                    ? '条件に一致するミーティングがありません'
                    : 'ミーティングがありません'
                  }
                </div>
              ) : (
                (viewMode === 'upcoming' ? upcomingMeetings : filteredMeetings).map((meeting) => (
                  <div
                    key={meeting.id}
                    className="p-6 hover:bg-gray-50 cursor-pointer"
                    onClick={() => setSelectedMeeting(meeting)}
                  >
                    <div className="flex items-start justify-between">
                      <div className="flex-1">
                        <div className="flex items-center gap-3 mb-2">
                          <Calendar className="w-5 h-5 text-gray-400" />
                          <span className="text-lg font-medium text-gray-900">
                            {formatDate(meeting.scheduledAt)}
                          </span>
                          <span className={`px-3 py-1 rounded-full text-xs ${getStatusColor(meeting.status)}`}>
                            {getStatusText(meeting.status)}
                          </span>
                        </div>
                        {meeting.customAgenda && (
                          <p className="text-gray-600 ml-8 line-clamp-2">
                            {meeting.customAgenda}
                          </p>
                        )}
                      </div>
                      <FileText className="w-5 h-5 text-gray-400" />
                    </div>
                  </div>
                ))
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
