-- V24: organization_membersテーブルのroleカラムCHECK制約を更新
-- OrganizationRole enumに合わせて拡張された役割を許可する
-- 作成日: 2025-11-21

-- H2データベースの場合、テーブル再作成が必要
-- 1. 一時テーブルを作成してデータを退避
CREATE TABLE organization_members_temp AS SELECT * FROM organization_members;

-- 2. 元のテーブルを削除
DROP TABLE organization_members;

-- 3. 新しいCHECK制約でテーブルを再作成
CREATE TABLE organization_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'MEMBER',
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    UNIQUE (organization_id, user_id),
    CHECK (role IN ('OWNER', 'ADMIN_ROOT', 'ADMIN_CORE', 'ADMIN_LEAD', 'ADMIN_SUPER', 'MEMBER', 'ADMIN', 'MODERATOR'))
);

-- 4. インデックスを再作成
CREATE INDEX idx_organization_members_tenant ON organization_members(tenant_id);
CREATE INDEX idx_organization_members_organization ON organization_members(organization_id);
CREATE INDEX idx_organization_members_user ON organization_members(user_id);
CREATE INDEX idx_organization_members_role ON organization_members(role);
CREATE INDEX idx_organization_members_tenant_user ON organization_members(tenant_id, user_id);
CREATE INDEX idx_organization_members_is_primary ON organization_members(is_primary);

-- 5. データを戻す
INSERT INTO organization_members (id, tenant_id, organization_id, user_id, role, is_primary, joined_at)
SELECT id, tenant_id, organization_id, user_id, role, is_primary, joined_at FROM organization_members_temp;

-- 6. 一時テーブルを削除
DROP TABLE organization_members_temp;
