-- V5: テナント管理テーブルの作成
-- 企業向け匿名進捗・目標開示プラットフォーム対応
-- 作成日: 2025-11-07

-- テナント（企業・組織）テーブル
CREATE TABLE IF NOT EXISTS tenants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    slug VARCHAR(100) NOT NULL UNIQUE,
    plan_type VARCHAR(20) NOT NULL DEFAULT 'FREE',
    max_users INT NOT NULL DEFAULT 50,
    max_storage_gb INT NOT NULL DEFAULT 5,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    contact_email VARCHAR(100),
    settings VARCHAR(4000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CHECK (plan_type IN ('FREE', 'PRO', 'ENTERPRISE')),
    CHECK (status IN ('ACTIVE', 'SUSPENDED', 'CLOSED')),
    CHECK (max_users > 0),
    CHECK (max_storage_gb > 0)
);

CREATE INDEX idx_tenants_slug ON tenants(slug);
CREATE INDEX idx_tenants_status ON tenants(status);
CREATE INDEX idx_tenants_plan_type ON tenants(plan_type);
CREATE INDEX idx_tenants_created_at ON tenants(created_at);

-- デフォルトテナントを作成（既存データの移行用）
INSERT INTO tenants (name, slug, plan_type, status, max_users, max_storage_gb, contact_email)
VALUES ('Default Organization', 'default', 'FREE', 'ACTIVE', 100, 10, 'admin@example.com');

-- テナント招待テーブル（将来の機能用）
CREATE TABLE IF NOT EXISTS tenant_invitations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    email VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'USER',
    invite_code VARCHAR(64) NOT NULL UNIQUE,
    invited_by BIGINT,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    expires_at TIMESTAMP NOT NULL,
    accepted_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CHECK (role IN ('TENANT_ADMIN', 'ORG_ADMIN', 'MODERATOR', 'USER')),
    CHECK (status IN ('PENDING', 'ACCEPTED', 'EXPIRED', 'CANCELLED'))
);

CREATE INDEX idx_tenant_invitations_tenant ON tenant_invitations(tenant_id);
CREATE INDEX idx_tenant_invitations_email ON tenant_invitations(email);
CREATE INDEX idx_tenant_invitations_invite_code ON tenant_invitations(invite_code);
CREATE INDEX idx_tenant_invitations_status ON tenant_invitations(status);
CREATE INDEX idx_tenant_invitations_expires_at ON tenant_invitations(expires_at);
