-- V6: 組織階層管理テーブルの作成
-- 会社→本部→部→課→チーム のような階層構造をサポート
-- 作成日: 2025-11-07

-- 組織階層テーブル
CREATE TABLE IF NOT EXISTS organizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    parent_id BIGINT,
    name VARCHAR(200) NOT NULL,
    organization_type VARCHAR(50),
    description TEXT,
    level INT NOT NULL DEFAULT 1,
    path VARCHAR(1000),
    display_order INT NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    FOREIGN KEY (parent_id) REFERENCES organizations(id) ON DELETE CASCADE
);

CREATE INDEX idx_organizations_tenant ON organizations(tenant_id);
CREATE INDEX idx_organizations_parent ON organizations(parent_id);
CREATE INDEX idx_organizations_path ON organizations(path);
CREATE INDEX idx_organizations_level ON organizations(level);
CREATE INDEX idx_organizations_is_active ON organizations(is_active);
CREATE INDEX idx_organizations_tenant_active ON organizations(tenant_id, is_active);
CREATE INDEX idx_organizations_tenant_parent ON organizations(tenant_id, parent_id);
CREATE INDEX idx_organizations_display_order ON organizations(display_order);

-- デフォルトテナントのルート組織を作成
INSERT INTO organizations (tenant_id, parent_id, name, organization_type, level, path)
VALUES (1, NULL, 'Default Organization', 'COMPANY', 1, '/1');

-- 組織メンバーシップテーブル
CREATE TABLE IF NOT EXISTS organization_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'MEMBER',
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    UNIQUE (organization_id, user_id),
    CHECK (role IN ('OWNER', 'ADMIN', 'MODERATOR', 'MEMBER'))
);

CREATE INDEX idx_organization_members_tenant ON organization_members(tenant_id);
CREATE INDEX idx_organization_members_organization ON organization_members(organization_id);
CREATE INDEX idx_organization_members_user ON organization_members(user_id);
CREATE INDEX idx_organization_members_role ON organization_members(role);
CREATE INDEX idx_organization_members_tenant_user ON organization_members(tenant_id, user_id);
CREATE INDEX idx_organization_members_is_primary ON organization_members(is_primary);

-- 匿名プロフィールテーブル
CREATE TABLE IF NOT EXISTS anonymous_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    anonymous_id VARCHAR(100) NOT NULL,
    display_name VARCHAR(100),
    avatar_url VARCHAR(500),
    anonymity_level VARCHAR(20) NOT NULL DEFAULT 'PSEUDONYM',
    bio TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    UNIQUE (organization_id, user_id),
    UNIQUE (tenant_id, anonymous_id),
    CHECK (anonymity_level IN ('FULL', 'PSEUDONYM', 'REAL'))
);

CREATE INDEX idx_anonymous_profiles_tenant ON anonymous_profiles(tenant_id);
CREATE INDEX idx_anonymous_profiles_organization ON anonymous_profiles(organization_id);
CREATE INDEX idx_anonymous_profiles_user ON anonymous_profiles(user_id);
CREATE INDEX idx_anonymous_profiles_anonymous_id ON anonymous_profiles(anonymous_id);
CREATE INDEX idx_anonymous_profiles_anonymity_level ON anonymous_profiles(anonymity_level);

-- ポリシー設定テーブル
CREATE TABLE IF NOT EXISTS policy_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL,

    -- 匿名性ポリシー
    default_anonymity_level VARCHAR(20) NOT NULL DEFAULT 'PSEUDONYM',
    allow_full_anonymous BOOLEAN NOT NULL DEFAULT TRUE,
    allow_real_name BOOLEAN NOT NULL DEFAULT TRUE,

    -- 公開範囲ポリシー
    default_visibility VARCHAR(20) NOT NULL DEFAULT 'ORGANIZATION',
    allow_company_wide BOOLEAN NOT NULL DEFAULT FALSE,

    -- 投稿制限
    require_approval BOOLEAN NOT NULL DEFAULT FALSE,
    min_post_length INT NOT NULL DEFAULT 10,
    max_post_length INT NOT NULL DEFAULT 5000,

    -- モデレーション
    enable_ng_word_filter BOOLEAN NOT NULL DEFAULT TRUE,
    enable_auto_moderation BOOLEAN NOT NULL DEFAULT TRUE,
    ng_words VARCHAR(4000),

    -- その他
    settings VARCHAR(4000),

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
    UNIQUE (organization_id),
    CHECK (default_anonymity_level IN ('FULL', 'PSEUDONYM', 'REAL')),
    CHECK (default_visibility IN ('PRIVATE', 'TEAM', 'DEPARTMENT', 'ORGANIZATION', 'COMPANY')),
    CHECK (min_post_length > 0),
    CHECK (max_post_length >= min_post_length)
);

CREATE INDEX idx_policy_settings_tenant ON policy_settings(tenant_id);
CREATE INDEX idx_policy_settings_organization ON policy_settings(organization_id);

-- デフォルト組織のポリシーを作成
INSERT INTO policy_settings (tenant_id, organization_id, default_anonymity_level, default_visibility)
VALUES (1, 1, 'PSEUDONYM', 'ORGANIZATION');
