-- V7: 進捗投稿関連テーブルの作成
-- 日々の目標・進捗・課題を記録し、リアクション機能をサポート
-- 作成日: 2025-11-07

-- 進捗投稿テーブル
CREATE TABLE IF NOT EXISTS progress_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    is_anonymous BOOLEAN NOT NULL DEFAULT TRUE,

    -- 投稿内容
    post_type VARCHAR(20) NOT NULL DEFAULT 'PROGRESS',
    title VARCHAR(200),
    content TEXT NOT NULL,
    achievement_rate INT,
    blockers TEXT,
    learnings TEXT,
    next_action TEXT,

    -- 公開範囲
    visibility VARCHAR(20) NOT NULL DEFAULT 'ORGANIZATION',
    target_organization_id BIGINT,

    -- メタデータ
    post_date DATE NOT NULL,
    tags VARCHAR(4000),
    attachments VARCHAR(4000),

    -- 統計
    reaction_count INT NOT NULL DEFAULT 0,
    comment_count INT NOT NULL DEFAULT 0,
    view_count INT NOT NULL DEFAULT 0,

    -- 管理
    is_pinned BOOLEAN NOT NULL DEFAULT FALSE,
    is_archived BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_progress_posts_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_progress_posts_organization FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
    CONSTRAINT fk_progress_posts_author FOREIGN KEY (author_id) REFERENCES anonymous_profiles(id) ON DELETE CASCADE,
    CONSTRAINT fk_progress_posts_target_org FOREIGN KEY (target_organization_id) REFERENCES organizations(id) ON DELETE SET NULL,
    CONSTRAINT chk_progress_posts_type CHECK (post_type IN ('PROGRESS', 'GOAL', 'BLOCKER', 'LEARNING', 'REFLECTION')),
    CONSTRAINT chk_progress_posts_visibility CHECK (visibility IN ('PRIVATE', 'TEAM', 'DEPARTMENT', 'ORGANIZATION', 'COMPANY')),
    CONSTRAINT chk_progress_posts_achievement CHECK (achievement_rate IS NULL OR (achievement_rate >= 0 AND achievement_rate <= 100))
);

CREATE INDEX idx_progress_posts_tenant ON progress_posts(tenant_id);
CREATE INDEX idx_progress_posts_organization ON progress_posts(organization_id);
CREATE INDEX idx_progress_posts_author ON progress_posts(author_id);
CREATE INDEX idx_progress_posts_post_date ON progress_posts(post_date);
CREATE INDEX idx_progress_posts_post_type ON progress_posts(post_type);
CREATE INDEX idx_progress_posts_visibility ON progress_posts(visibility);
CREATE INDEX idx_progress_posts_is_archived ON progress_posts(is_archived);
CREATE INDEX idx_progress_posts_tenant_date ON progress_posts(tenant_id, post_date DESC);
CREATE INDEX idx_progress_posts_org_date ON progress_posts(organization_id, post_date DESC);
CREATE INDEX idx_progress_posts_tenant_org_date ON progress_posts(tenant_id, organization_id, post_date DESC);
CREATE INDEX idx_progress_posts_author_date ON progress_posts(author_id, post_date DESC);


-- 投稿リアクションテーブル
CREATE TABLE IF NOT EXISTS post_reactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    post_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    is_anonymous BOOLEAN NOT NULL DEFAULT TRUE,

    reaction_type VARCHAR(20) NOT NULL,
    comment TEXT,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_post_reactions_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_post_reactions_post FOREIGN KEY (post_id) REFERENCES progress_posts(id) ON DELETE CASCADE,
    CONSTRAINT fk_post_reactions_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uq_post_reactions_post_user_type UNIQUE (post_id, user_id, reaction_type),
    CONSTRAINT chk_post_reactions_type CHECK (reaction_type IN ('PRAISE', 'EMPATHY', 'SUPPORT', 'QUESTION', 'HEART', 'THUMBS_UP', 'FIRE', 'CLAP'))
);

CREATE INDEX idx_post_reactions_tenant ON post_reactions(tenant_id);
CREATE INDEX idx_post_reactions_post ON post_reactions(post_id);
CREATE INDEX idx_post_reactions_user ON post_reactions(user_id);
CREATE INDEX idx_post_reactions_type ON post_reactions(reaction_type);
CREATE INDEX idx_post_reactions_tenant_post ON post_reactions(tenant_id, post_id);
CREATE INDEX idx_post_reactions_created_at ON post_reactions(created_at DESC);


-- 投稿コメントテーブル
CREATE TABLE IF NOT EXISTS post_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    post_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    parent_comment_id BIGINT,
    is_anonymous BOOLEAN NOT NULL DEFAULT TRUE,

    content TEXT NOT NULL,

    -- 統計
    reaction_count INT NOT NULL DEFAULT 0,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_post_comments_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_post_comments_post FOREIGN KEY (post_id) REFERENCES progress_posts(id) ON DELETE CASCADE,
    CONSTRAINT fk_post_comments_author FOREIGN KEY (author_id) REFERENCES anonymous_profiles(id) ON DELETE CASCADE,
    CONSTRAINT fk_post_comments_parent FOREIGN KEY (parent_comment_id) REFERENCES post_comments(id) ON DELETE CASCADE
);

CREATE INDEX idx_post_comments_tenant ON post_comments(tenant_id);
CREATE INDEX idx_post_comments_post ON post_comments(post_id);
CREATE INDEX idx_post_comments_author ON post_comments(author_id);
CREATE INDEX idx_post_comments_parent ON post_comments(parent_comment_id);
CREATE INDEX idx_post_comments_post_created ON post_comments(post_id, created_at DESC);
CREATE INDEX idx_post_comments_created_at ON post_comments(created_at DESC);


-- 投稿閲覧履歴テーブル（統計用）
CREATE TABLE IF NOT EXISTS post_views (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    post_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    viewed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_post_views_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_post_views_post FOREIGN KEY (post_id) REFERENCES progress_posts(id) ON DELETE CASCADE,
    CONSTRAINT fk_post_views_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uq_post_views_post_user UNIQUE (post_id, user_id)
);

CREATE INDEX idx_post_views_tenant ON post_views(tenant_id);
CREATE INDEX idx_post_views_post ON post_views(post_id);
CREATE INDEX idx_post_views_user ON post_views(user_id);
CREATE INDEX idx_post_views_viewed_at ON post_views(viewed_at DESC);

