-- V7: 進捗投稿関連テーブルの作成
-- 日々の目標・進捗・課題を記録し、リアクション機能をサポート
-- 作成日: 2025-11-07

-- 進捗投稿テーブル
CREATE TABLE IF NOT EXISTS progress_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    is_anonymous BOOLEAN NOT NULL DEFAULT TRUE,

    -- 投稿内容
    post_type VARCHAR(20) NOT NULL DEFAULT 'PROGRESS',
    title VARCHAR(200),
    content TEXT NOT NULL,
    achievement_rate INT,
    blockers TEXT,
    learnings TEXT,
    next_action TEXT,

    -- 公開範囲
    visibility VARCHAR(20) NOT NULL DEFAULT 'ORGANIZATION',
    target_organization_id BIGINT,

    -- メタデータ
    post_date DATE NOT NULL,
    tags VARCHAR(4000),
    attachments VARCHAR(4000),

    -- 統計
    reaction_count INT NOT NULL DEFAULT 0,
    comment_count INT NOT NULL DEFAULT 0,
    view_count INT NOT NULL DEFAULT 0,

    -- 管理
    is_pinned BOOLEAN NOT NULL DEFAULT FALSE,
    is_archived BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
    FOREIGN KEY (author_id) REFERENCES anonymous_profiles(id) ON DELETE CASCADE,
    FOREIGN KEY (target_organization_id) REFERENCES organizations(id) ON DELETE SET NULL,
    INDEX idx_tenant (tenant_id),
    INDEX idx_organization (organization_id),
    INDEX idx_author (author_id),
    INDEX idx_post_date (post_date),
    INDEX idx_post_type (post_type),
    INDEX idx_visibility (visibility),
    INDEX idx_is_archived (is_archived),
    INDEX idx_tenant_date (tenant_id, post_date DESC),
    INDEX idx_org_date (organization_id, post_date DESC),
    INDEX idx_tenant_org_date (tenant_id, organization_id, post_date DESC),
    INDEX idx_author_date (author_id, post_date DESC),
    CHECK (post_type IN ('PROGRESS', 'GOAL', 'BLOCKER', 'LEARNING', 'REFLECTION')),
    CHECK (visibility IN ('PRIVATE', 'TEAM', 'DEPARTMENT', 'ORGANIZATION', 'COMPANY')),
    CHECK (achievement_rate IS NULL OR (achievement_rate >= 0 AND achievement_rate <= 100))
);


-- 投稿リアクションテーブル
CREATE TABLE IF NOT EXISTS post_reactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    post_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    is_anonymous BOOLEAN NOT NULL DEFAULT TRUE,

    reaction_type VARCHAR(20) NOT NULL,
    comment TEXT,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    FOREIGN KEY (post_id) REFERENCES progress_posts(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    UNIQUE (post_id, user_id, reaction_type),
    INDEX idx_tenant (tenant_id),
    INDEX idx_post (post_id),
    INDEX idx_user (user_id),
    INDEX idx_reaction_type (reaction_type),
    INDEX idx_tenant_post (tenant_id, post_id),
    INDEX idx_created_at (created_at DESC),
    CHECK (reaction_type IN ('PRAISE', 'EMPATHY', 'SUPPORT', 'QUESTION', 'HEART', 'THUMBS_UP', 'FIRE', 'CLAP'))
);


-- 投稿コメントテーブル
CREATE TABLE IF NOT EXISTS post_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    post_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    parent_comment_id BIGINT,
    is_anonymous BOOLEAN NOT NULL DEFAULT TRUE,

    content TEXT NOT NULL,

    -- 統計
    reaction_count INT NOT NULL DEFAULT 0,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    FOREIGN KEY (post_id) REFERENCES progress_posts(id) ON DELETE CASCADE,
    FOREIGN KEY (author_id) REFERENCES anonymous_profiles(id) ON DELETE CASCADE,
    FOREIGN KEY (parent_comment_id) REFERENCES post_comments(id) ON DELETE CASCADE,
    INDEX idx_tenant (tenant_id),
    INDEX idx_post (post_id),
    INDEX idx_author (author_id),
    INDEX idx_parent (parent_comment_id),
    INDEX idx_post_created (post_id, created_at DESC),
    INDEX idx_created_at (created_at DESC)
);


-- 投稿閲覧履歴テーブル（統計用）
CREATE TABLE IF NOT EXISTS post_views (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    post_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    viewed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    FOREIGN KEY (post_id) REFERENCES progress_posts(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    UNIQUE (post_id, user_id),
    INDEX idx_tenant (tenant_id),
    INDEX idx_post (post_id),
    INDEX idx_user (user_id),
    INDEX idx_viewed_at (viewed_at DESC)
);

