-- V8: OKR（Objectives and Key Results）管理テーブルの作成
-- 目標管理と進捗投稿を紐付けるためのテーブル
-- 作成日: 2025-11-07

-- OKR目標テーブル
CREATE TABLE IF NOT EXISTS okr_objectives (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    organization_id BIGINT,
    owner_id BIGINT,
    parent_objective_id BIGINT,

    title VARCHAR(300) NOT NULL,
    description TEXT,
    target_quarter VARCHAR(10),
    start_date DATE,
    end_date DATE,

    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    progress_rate INT NOT NULL DEFAULT 0,
    confidence_level VARCHAR(20),

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP NULL,

    CONSTRAINT fk_okr_objectives_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_okr_objectives_organization FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
    CONSTRAINT fk_okr_objectives_owner FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_okr_objectives_parent FOREIGN KEY (parent_objective_id) REFERENCES okr_objectives(id) ON DELETE CASCADE,
    CONSTRAINT chk_okr_objectives_status CHECK (status IN ('DRAFT', 'ACTIVE', 'COMPLETED', 'CANCELLED', 'ON_HOLD')),
    CONSTRAINT chk_okr_objectives_progress CHECK (progress_rate >= 0 AND progress_rate <= 100),
    CONSTRAINT chk_okr_objectives_confidence CHECK (confidence_level IS NULL OR confidence_level IN ('HIGH', 'MEDIUM', 'LOW', 'AT_RISK'))
);

CREATE INDEX idx_okr_objectives_tenant ON okr_objectives(tenant_id);
CREATE INDEX idx_okr_objectives_organization ON okr_objectives(organization_id);
CREATE INDEX idx_okr_objectives_owner ON okr_objectives(owner_id);
CREATE INDEX idx_okr_objectives_parent ON okr_objectives(parent_objective_id);
CREATE INDEX idx_okr_objectives_quarter ON okr_objectives(target_quarter);
CREATE INDEX idx_okr_objectives_status ON okr_objectives(status);
CREATE INDEX idx_okr_objectives_tenant_quarter ON okr_objectives(tenant_id, target_quarter);
CREATE INDEX idx_okr_objectives_tenant_status ON okr_objectives(tenant_id, status);
CREATE INDEX idx_okr_objectives_org_quarter ON okr_objectives(organization_id, target_quarter);

-- OKR主要結果テーブル
CREATE TABLE IF NOT EXISTS okr_key_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    objective_id BIGINT NOT NULL,

    title VARCHAR(300) NOT NULL,
    description TEXT,
    metric_type VARCHAR(20) NOT NULL,
    baseline_value DECIMAL(15,2),
    target_value DECIMAL(15,2) NOT NULL,
    current_value DECIMAL(15,2) NOT NULL DEFAULT 0,
    unit VARCHAR(50),

    progress_rate INT NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP NULL,

    CONSTRAINT fk_okr_key_results_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_okr_key_results_objective FOREIGN KEY (objective_id) REFERENCES okr_objectives(id) ON DELETE CASCADE,
    CONSTRAINT chk_okr_key_results_metric CHECK (metric_type IN ('NUMBER', 'PERCENTAGE', 'BOOLEAN', 'CURRENCY')),
    CONSTRAINT chk_okr_key_results_status CHECK (status IN ('ACTIVE', 'COMPLETED', 'CANCELLED', 'ON_HOLD')),
    CONSTRAINT chk_okr_key_results_progress CHECK (progress_rate >= 0 AND progress_rate <= 100)
);

CREATE INDEX idx_okr_key_results_tenant ON okr_key_results(tenant_id);
CREATE INDEX idx_okr_key_results_objective ON okr_key_results(objective_id);
CREATE INDEX idx_okr_key_results_status ON okr_key_results(status);
CREATE INDEX idx_okr_key_results_tenant_objective ON okr_key_results(tenant_id, objective_id);

-- 投稿とOKRの紐付けテーブル
CREATE TABLE IF NOT EXISTS post_okr_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    post_id BIGINT NOT NULL,
    objective_id BIGINT,
    key_result_id BIGINT,
    contribution_note TEXT,
    impact_score INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_post_okr_links_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_post_okr_links_post FOREIGN KEY (post_id) REFERENCES progress_posts(id) ON DELETE CASCADE,
    CONSTRAINT fk_post_okr_links_objective FOREIGN KEY (objective_id) REFERENCES okr_objectives(id) ON DELETE CASCADE,
    CONSTRAINT fk_post_okr_links_key_result FOREIGN KEY (key_result_id) REFERENCES okr_key_results(id) ON DELETE CASCADE,
    CONSTRAINT chk_post_okr_links_entity CHECK (objective_id IS NOT NULL OR key_result_id IS NOT NULL),
    CONSTRAINT chk_post_okr_links_impact CHECK (impact_score IS NULL OR (impact_score >= 1 AND impact_score <= 5))
);

CREATE INDEX idx_post_okr_links_tenant ON post_okr_links(tenant_id);
CREATE INDEX idx_post_okr_links_post ON post_okr_links(post_id);
CREATE INDEX idx_post_okr_links_objective ON post_okr_links(objective_id);
CREATE INDEX idx_post_okr_links_key_result ON post_okr_links(key_result_id);
CREATE INDEX idx_post_okr_links_tenant_post ON post_okr_links(tenant_id, post_id);
CREATE INDEX idx_post_okr_links_tenant_objective ON post_okr_links(tenant_id, objective_id);

-- OKR更新履歴テーブル（進捗の変遷を記録）
CREATE TABLE IF NOT EXISTS okr_update_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    objective_id BIGINT,
    key_result_id BIGINT,

    field_name VARCHAR(50) NOT NULL,
    old_value TEXT,
    new_value TEXT,
    updated_by BIGINT NULL,
    update_note TEXT,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_okr_update_history_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_okr_update_history_objective FOREIGN KEY (objective_id) REFERENCES okr_objectives(id) ON DELETE CASCADE,
    CONSTRAINT fk_okr_update_history_key_result FOREIGN KEY (key_result_id) REFERENCES okr_key_results(id) ON DELETE CASCADE,
    CONSTRAINT fk_okr_update_history_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT chk_okr_update_history_entity CHECK (objective_id IS NOT NULL OR key_result_id IS NOT NULL)
);

CREATE INDEX idx_okr_update_history_tenant ON okr_update_history(tenant_id);
CREATE INDEX idx_okr_update_history_objective ON okr_update_history(objective_id);
CREATE INDEX idx_okr_update_history_key_result ON okr_update_history(key_result_id);
CREATE INDEX idx_okr_update_history_created_at ON okr_update_history(created_at DESC);

-- 評価スナップショットテーブル
CREATE TABLE IF NOT EXISTS evaluation_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL,

    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    period_label VARCHAR(100),

    -- 集計データ
    total_posts INT NOT NULL DEFAULT 0,
    total_achievements INT NOT NULL DEFAULT 0,
    avg_achievement_rate DECIMAL(5,2),
    total_reactions_received INT NOT NULL DEFAULT 0,
    total_okr_contributions INT NOT NULL DEFAULT 0,
    completed_objectives INT NOT NULL DEFAULT 0,
    completed_key_results INT NOT NULL DEFAULT 0,

    -- エクスポート情報
    snapshot_data VARCHAR(10000),
    exported_at TIMESTAMP NULL,
    export_format VARCHAR(20),
    export_file_url VARCHAR(500),

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_evaluation_snapshots_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_evaluation_snapshots_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_evaluation_snapshots_organization FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
    CONSTRAINT chk_evaluation_snapshots_format CHECK (export_format IS NULL OR export_format IN ('PDF', 'CSV', 'JSON'))
);

CREATE INDEX idx_evaluation_snapshots_tenant ON evaluation_snapshots(tenant_id);
CREATE INDEX idx_evaluation_snapshots_user ON evaluation_snapshots(user_id);
CREATE INDEX idx_evaluation_snapshots_organization ON evaluation_snapshots(organization_id);
CREATE INDEX idx_evaluation_snapshots_period ON evaluation_snapshots(period_start, period_end);
CREATE INDEX idx_evaluation_snapshots_tenant_user_period ON evaluation_snapshots(tenant_id, user_id, period_start);
CREATE INDEX idx_evaluation_snapshots_period_label ON evaluation_snapshots(period_label);

-- 監査ログテーブル
CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    user_id BIGINT,

    action VARCHAR(100) NOT NULL,
    entity_type VARCHAR(50),
    entity_id BIGINT,

    details VARCHAR(10000),
    ip_address VARCHAR(45),
    user_agent TEXT,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_audit_logs_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_audit_logs_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX idx_audit_logs_tenant ON audit_logs(tenant_id);
CREATE INDEX idx_audit_logs_user ON audit_logs(user_id);
CREATE INDEX idx_audit_logs_action ON audit_logs(action);
CREATE INDEX idx_audit_logs_entity ON audit_logs(entity_type, entity_id);
CREATE INDEX idx_audit_logs_created_at ON audit_logs(created_at DESC);
CREATE INDEX idx_audit_logs_tenant_action ON audit_logs(tenant_id, action);
CREATE INDEX idx_audit_logs_tenant_created ON audit_logs(tenant_id, created_at DESC);
