package com.chatapp.service;

import com.chatapp.model.*;
import com.chatapp.repository.OneOnOneMeetingRepository;
import com.chatapp.repository.ProgressPostRepository;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.List;
import java.util.stream.Collectors;

@Service
public class OneOnOneMeetingService {

    private final OneOnOneMeetingRepository meetingRepository;
    private final ProgressPostRepository progressPostRepository;

    public OneOnOneMeetingService(OneOnOneMeetingRepository meetingRepository,
                                  ProgressPostRepository progressPostRepository) {
        this.meetingRepository = meetingRepository;
        this.progressPostRepository = progressPostRepository;
    }

    /**
     * 1on1ミーティングを作成
     */
    @Transactional
    public OneOnOneMeeting createMeeting(User employee, User manager, Tenant tenant,
                                         LocalDateTime scheduledAt) {
        OneOnOneMeeting meeting = new OneOnOneMeeting();
        meeting.setEmployee(employee);
        meeting.setManager(manager);
        meeting.setTenant(tenant);
        meeting.setScheduledAt(scheduledAt);
        meeting.setStatus(OneOnOneMeeting.MeetingStatus.SCHEDULED);

        // アジェンダを自動生成
        String autoGeneratedAgenda = generateAgenda(employee, tenant, scheduledAt);
        meeting.setAutoGeneratedAgenda(autoGeneratedAgenda);

        return meetingRepository.save(meeting);
    }

    /**
     * アジェンダを自動生成
     */
    public String generateAgenda(User employee, Tenant tenant, LocalDateTime scheduledAt) {
        // 前回のミーティングから今回までの進捗投稿を取得
        LocalDateTime twoWeeksAgo = scheduledAt.minusWeeks(2);
        List<ProgressPost> recentPosts = progressPostRepository.findByAuthorAndCreatedAtBetween(
                employee, twoWeeksAgo, scheduledAt);

        StringBuilder agenda = new StringBuilder();
        agenda.append("# 1on1ミーティング アジェンダ\n\n");
        agenda.append(String.format("日時: %s\n\n", scheduledAt.toLocalDate()));

        // 1. 最近の達成事項
        agenda.append("## 1. 最近の達成事項\n\n");
        List<String> achievements = recentPosts.stream()
                .map(ProgressPost::getContent)
                .filter(a -> a != null && !a.isEmpty())
                .limit(5)
                .collect(Collectors.toList());

        if (achievements.isEmpty()) {
            agenda.append("- （記録なし）\n\n");
        } else {
            achievements.forEach(a -> agenda.append(String.format("- %s\n", a)));
            agenda.append("\n");
        }

        // 2. 現在の課題
        agenda.append("## 2. 現在の課題・困っていること\n\n");
        List<String> blockers = recentPosts.stream()
                .map(ProgressPost::getBlockers)
                .filter(c -> c != null && !c.isEmpty())
                .distinct()
                .limit(5)
                .collect(Collectors.toList());

        if (blockers.isEmpty()) {
            agenda.append("- （記録なし）\n\n");
        } else {
            blockers.forEach(c -> agenda.append(String.format("- %s\n", c)));
            agenda.append("\n");
        }

        // 3. 学び・気づき
        agenda.append("## 3. 学び・気づき\n\n");
        List<String> learnings = recentPosts.stream()
                .map(ProgressPost::getLearnings)
                .filter(l -> l != null && !l.isEmpty())
                .limit(5)
                .collect(Collectors.toList());

        if (learnings.isEmpty()) {
            agenda.append("- （記録なし）\n\n");
        } else {
            learnings.forEach(l -> agenda.append(String.format("- %s\n", l)));
            agenda.append("\n");
        }

        // 4. 次の目標
        agenda.append("## 4. 今後の目標・取り組み\n\n");
        List<String> nextActions = recentPosts.stream()
                .map(ProgressPost::getNextAction)
                .filter(g -> g != null && !g.isEmpty())
                .limit(5)
                .collect(Collectors.toList());

        if (nextActions.isEmpty()) {
            agenda.append("- （記録なし）\n\n");
        } else {
            nextActions.forEach(g -> agenda.append(String.format("- %s\n", g)));
            agenda.append("\n");
        }

        // 5. ディスカッションポイント
        agenda.append("## 5. ディスカッションポイント\n\n");
        agenda.append("- キャリア目標について\n");
        agenda.append("- スキル開発の機会\n");
        agenda.append("- チームや組織への提案\n");
        agenda.append("- その他フィードバック\n\n");

        agenda.append("---\n");
        agenda.append("※ このアジェンダは進捗投稿から自動生成されました。\n");
        agenda.append("※ 必要に応じて編集・追加してください。\n");

        return agenda.toString();
    }

    /**
     * ミーティングを更新
     */
    @Transactional
    public OneOnOneMeeting updateMeeting(Long meetingId, String customAgenda,
                                         String discussionTopics, String actionItems,
                                         String notes) {
        OneOnOneMeeting meeting = meetingRepository.findById(meetingId)
                .orElseThrow(() -> new RuntimeException("Meeting not found"));

        if (customAgenda != null) {
            meeting.setCustomAgenda(customAgenda);
        }
        if (discussionTopics != null) {
            meeting.setDiscussionTopics(discussionTopics);
        }
        if (actionItems != null) {
            meeting.setActionItems(actionItems);
        }
        if (notes != null) {
            meeting.setNotes(notes);
        }

        return meetingRepository.save(meeting);
    }

    /**
     * ミーティングを完了にする
     */
    @Transactional
    public OneOnOneMeeting completeMeeting(Long meetingId) {
        OneOnOneMeeting meeting = meetingRepository.findById(meetingId)
                .orElseThrow(() -> new RuntimeException("Meeting not found"));

        meeting.setStatus(OneOnOneMeeting.MeetingStatus.COMPLETED);
        meeting.setCompletedAt(LocalDateTime.now());

        return meetingRepository.save(meeting);
    }

    /**
     * 従業員のミーティング一覧を取得
     */
    @Transactional(readOnly = true)
    public Page<OneOnOneMeeting> getEmployeeMeetings(User employee, Tenant tenant, Pageable pageable) {
        return meetingRepository.findByEmployeeAndTenantOrderByScheduledAtDesc(employee, tenant, pageable);
    }

    /**
     * マネージャーのミーティング一覧を取得
     */
    @Transactional(readOnly = true)
    public Page<OneOnOneMeeting> getManagerMeetings(User manager, Tenant tenant, Pageable pageable) {
        return meetingRepository.findByManagerAndTenantOrderByScheduledAtDesc(manager, tenant, pageable);
    }

    /**
     * 今後のミーティング一覧を取得
     */
    @Transactional(readOnly = true)
    public List<OneOnOneMeeting> getUpcomingMeetings(User user, Tenant tenant) {
        return meetingRepository.findUpcomingMeetings(tenant, user, LocalDateTime.now());
    }
}
