package com.chatapp.service;

import com.chatapp.model.*;
import com.chatapp.model.enums.PostType;
import com.chatapp.repository.*;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class ExportServiceTest {

    @Mock
    private ProgressPostRepository progressPostRepository;

    @Mock
    private OneOnOneMeetingRepository oneOnOneMeetingRepository;

    @Mock
    private UserRepository userRepository;

    @InjectMocks
    private ExportService exportService;

    private User testUser;
    private Tenant testTenant;
    private Organization testOrganization;
    private ProgressPost testProgressPost;
    private ProgressDigest testDigest;
    private OneOnOneMeeting testMeeting;

    @BeforeEach
    void setUp() {
        // Test tenant
        testTenant = new Tenant();
        testTenant.setId(1L);
        testTenant.setName("Test Company");
        testTenant.setSlug("testcompany");

        // Test organization
        testOrganization = new Organization();
        testOrganization.setId(1L);
        testOrganization.setTenant(testTenant);
        testOrganization.setName("Engineering");

        // Test user
        testUser = new User();
        testUser.setId(1L);
        testUser.setUsername("testuser");
        testUser.setEmail("test@example.com");
        testUser.setDisplayName("Test User");
        testUser.setTenantId(1L);
        testUser.setCreatedAt(LocalDateTime.now());

        // Test progress post
        testProgressPost = new ProgressPost();
        testProgressPost.setId(1L);
        testProgressPost.setTenant(testTenant);
        testProgressPost.setOrganization(testOrganization);
        testProgressPost.setAuthor(testUser);
        testProgressPost.setTitle("Test Progress");
        testProgressPost.setContent("Test progress content");
        testProgressPost.setPostType(PostType.PROGRESS);
        testProgressPost.setPostDate(LocalDate.now());
        testProgressPost.setAchievementRate(75);
        testProgressPost.setBlockers("No blockers");
        testProgressPost.setLearnings("Key learnings");
        testProgressPost.setNextAction("Next steps");
        testProgressPost.setTags(Arrays.asList("sprint", "backend"));
        testProgressPost.setCreatedAt(LocalDateTime.now());

        // Test digest
        testDigest = new ProgressDigest();
        testDigest.setId(1L);
        testDigest.setUser(testUser);
        testDigest.setTenant(testTenant);
        testDigest.setDigestType(ProgressDigest.DigestType.WEEKLY);
        testDigest.setPeriodStart(LocalDateTime.now().minusDays(7));
        testDigest.setPeriodEnd(LocalDateTime.now());
        testDigest.setTotalPosts(10);
        testDigest.setCompletedGoals(5);
        testDigest.setOngoingGoals(3);
        testDigest.setChallenges(2);
        testDigest.setSummary("Test weekly summary");
        testDigest.setTopAchievements("Achievement 1\nAchievement 2");
        testDigest.setTopChallenges("Challenge 1");
        testDigest.setKeyLearnings("Learning 1");
        testDigest.setNextSteps("Next step 1");
        testDigest.setCreatedAt(LocalDateTime.now());

        // Test meeting
        testMeeting = new OneOnOneMeeting();
        testMeeting.setId(1L);
        testMeeting.setEmployee(testUser);
        testMeeting.setManager(testUser);
        testMeeting.setTenant(testTenant);
        testMeeting.setScheduledAt(LocalDateTime.now());
        testMeeting.setAutoGeneratedAgenda("Test agenda");
        testMeeting.setCustomAgenda("Custom agenda");
        testMeeting.setDiscussionTopics("Discussion topics");
        testMeeting.setActionItems("Action items");
        testMeeting.setNotes("Meeting notes");
        testMeeting.setStatus(OneOnOneMeeting.MeetingStatus.COMPLETED);
        testMeeting.setCompletedAt(LocalDateTime.now());
        testMeeting.setCreatedAt(LocalDateTime.now());
    }

    @Test
    void testExportProgressPostsToCSV() throws IOException {
        // Arrange
        LocalDateTime startDate = LocalDateTime.now().minusDays(30);
        LocalDateTime endDate = LocalDateTime.now();
        when(progressPostRepository.findByAuthorAndCreatedAtBetween(
                eq(testUser), eq(startDate), eq(endDate))).thenReturn(Arrays.asList(testProgressPost));

        // Act
        byte[] csvData = exportService.exportProgressPostsToCSV(testUser, testTenant, startDate, endDate);

        // Assert
        assertNotNull(csvData);
        assertTrue(csvData.length > 0);
        String csvContent = new String(csvData);
        assertTrue(csvContent.contains("Test Progress"));
        assertTrue(csvContent.contains("Test progress content"));
        assertTrue(csvContent.contains("75"));
        verify(progressPostRepository, times(1))
                .findByAuthorAndCreatedAtBetween(eq(testUser), eq(startDate), eq(endDate));
    }

    @Test
    void testExportProgressPostsToExcel() throws Exception {
        // Arrange
        LocalDateTime startDate = LocalDateTime.now().minusDays(30);
        LocalDateTime endDate = LocalDateTime.now();
        when(progressPostRepository.findByAuthorAndCreatedAtBetween(
                eq(testUser), eq(startDate), eq(endDate))).thenReturn(Arrays.asList(testProgressPost));

        // Act
        byte[] excelData = exportService.exportProgressPostsToExcel(testUser, testTenant, startDate, endDate);

        // Assert
        assertNotNull(excelData);
        assertTrue(excelData.length > 0);

        // Verify Excel structure
        try (Workbook workbook = new XSSFWorkbook(new ByteArrayInputStream(excelData))) {
            Sheet sheet = workbook.getSheetAt(0);
            assertNotNull(sheet);

            // Check header row
            Row headerRow = sheet.getRow(0);
            assertEquals("日付", headerRow.getCell(0).getStringCellValue());
            assertEquals("タイトル", headerRow.getCell(1).getStringCellValue());

            // Check data row
            Row dataRow = sheet.getRow(1);
            assertNotNull(dataRow);
            assertEquals("Test Progress", dataRow.getCell(1).getStringCellValue());
        }

        verify(progressPostRepository, times(1))
                .findByAuthorAndCreatedAtBetween(eq(testUser), eq(startDate), eq(endDate));
    }

    @Test
    void testExportDigestToCSV() throws IOException {
        // Act
        byte[] csvData = exportService.exportDigestToCSV(testDigest);

        // Assert
        assertNotNull(csvData);
        assertTrue(csvData.length > 0);
        String csvContent = new String(csvData);
        assertTrue(csvContent.contains("WEEKLY"));
        assertTrue(csvContent.contains("10"));
    }

    @Test
    void testExportDigestToMarkdown() {
        // Act
        byte[] markdownData = exportService.exportDigestToMarkdown(testDigest);

        // Assert
        assertNotNull(markdownData);
        assertTrue(markdownData.length > 0);
        String markdownContent = new String(markdownData);
        assertTrue(markdownContent.contains("# 進捗ダイジェスト"));
        assertTrue(markdownContent.contains("WEEKLY"));
        assertTrue(markdownContent.contains("Achievement 1"));
    }

    @Test
    void testExportMeetingsToCSV() throws IOException {
        // Arrange
        LocalDateTime startDate = LocalDateTime.now().minusDays(30);
        LocalDateTime endDate = LocalDateTime.now();
        when(oneOnOneMeetingRepository.findByTenantAndStatusOrderByScheduledAtDesc(
                eq(testTenant), eq(OneOnOneMeeting.MeetingStatus.COMPLETED)))
                .thenReturn(Arrays.asList(testMeeting));

        // Act
        byte[] csvData = exportService.exportMeetingsToCSV(testUser, testTenant, startDate, endDate);

        // Assert
        assertNotNull(csvData);
        assertTrue(csvData.length > 0);
        String csvContent = new String(csvData);
        assertTrue(csvContent.contains("COMPLETED"));
        verify(oneOnOneMeetingRepository, times(1))
                .findByTenantAndStatusOrderByScheduledAtDesc(eq(testTenant), eq(OneOnOneMeeting.MeetingStatus.COMPLETED));
    }

    @Test
    void testExportMeetingsToExcel() throws Exception {
        // Arrange
        LocalDateTime startDate = LocalDateTime.now().minusDays(30);
        LocalDateTime endDate = LocalDateTime.now();
        when(oneOnOneMeetingRepository.findByTenantAndStatusOrderByScheduledAtDesc(
                eq(testTenant), eq(OneOnOneMeeting.MeetingStatus.COMPLETED)))
                .thenReturn(Arrays.asList(testMeeting));

        // Act
        byte[] excelData = exportService.exportMeetingsToExcel(testUser, testTenant, startDate, endDate);

        // Assert
        assertNotNull(excelData);
        assertTrue(excelData.length > 0);

        // Verify Excel structure
        try (Workbook workbook = new XSSFWorkbook(new ByteArrayInputStream(excelData))) {
            Sheet sheet = workbook.getSheetAt(0);
            assertNotNull(sheet);

            // Check header row
            Row headerRow = sheet.getRow(0);
            assertEquals("日付", headerRow.getCell(0).getStringCellValue());

            // Check data row
            Row dataRow = sheet.getRow(1);
            assertNotNull(dataRow);
        }

        verify(oneOnOneMeetingRepository, times(1))
                .findByTenantAndStatusOrderByScheduledAtDesc(eq(testTenant), eq(OneOnOneMeeting.MeetingStatus.COMPLETED));
    }

    @Test
    void testExportUsersToExcel() throws Exception {
        // Arrange
        List<User> users = Arrays.asList(testUser);
        when(userRepository.findByTenantId(1L)).thenReturn(users);

        // Act
        byte[] excelData = exportService.exportUsersToExcel(testTenant);

        // Assert
        assertNotNull(excelData);
        assertTrue(excelData.length > 0);

        // Verify Excel structure
        try (Workbook workbook = new XSSFWorkbook(new ByteArrayInputStream(excelData))) {
            Sheet sheet = workbook.getSheetAt(0);
            assertNotNull(sheet);

            // Check header row
            Row headerRow = sheet.getRow(0);
            assertEquals("ID", headerRow.getCell(0).getStringCellValue());
            assertEquals("ユーザー名", headerRow.getCell(1).getStringCellValue());

            // Check data row
            Row dataRow = sheet.getRow(1);
            assertEquals(1.0, dataRow.getCell(0).getNumericCellValue());
            assertEquals("testuser", dataRow.getCell(1).getStringCellValue());
        }

        verify(userRepository, times(1)).findByTenantId(1L);
    }

    @Test
    void testExportProgressPostsToCSV_EmptyList() throws IOException {
        // Arrange
        LocalDateTime startDate = LocalDateTime.now().minusDays(30);
        LocalDateTime endDate = LocalDateTime.now();
        when(progressPostRepository.findByAuthorAndCreatedAtBetween(
                any(User.class), any(LocalDateTime.class), any(LocalDateTime.class)))
                .thenReturn(Arrays.asList());

        // Act
        byte[] csvData = exportService.exportProgressPostsToCSV(testUser, testTenant, startDate, endDate);

        // Assert
        assertNotNull(csvData);
        String csvContent = new String(csvData);
        // Should contain only header
        assertTrue(csvContent.contains("日付"));
    }

    @Test
    void testExportDigestToMarkdown_WithNullFields() {
        // Arrange
        testDigest.setTopAchievements(null);
        testDigest.setTopChallenges(null);
        testDigest.setKeyLearnings(null);
        testDigest.setNextSteps(null);

        // Act
        byte[] markdownData = exportService.exportDigestToMarkdown(testDigest);

        // Assert
        assertNotNull(markdownData);
        assertTrue(markdownData.length > 0);
        String markdownContent = new String(markdownData);
        assertTrue(markdownContent.contains("# 進捗ダイジェスト"));
    }
}
