package com.chatapp.service;

import com.chatapp.model.*;
import com.chatapp.repository.*;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.io.ByteArrayInputStream;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyLong;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class ExportServiceTest {

    @Mock
    private ProgressPostRepository progressPostRepository;

    @Mock
    private ProgressDigestRepository progressDigestRepository;

    @Mock
    private OneOnOneMeetingRepository oneOnOneMeetingRepository;

    @Mock
    private UserRepository userRepository;

    @InjectMocks
    private ExportService exportService;

    private User testUser;
    private ProgressPost testProgressPost;
    private ProgressDigest testDigest;
    private OneOnOneMeeting testMeeting;

    @BeforeEach
    void setUp() {
        // Test user
        testUser = new User();
        testUser.setId(1L);
        testUser.setUsername("testuser");
        testUser.setEmail("test@example.com");
        testUser.setDisplayName("Test User");
        testUser.setTenantId(1L);

        // Test progress post
        testProgressPost = new ProgressPost();
        testProgressPost.setId(1L);
        testProgressPost.setUser(testUser);
        testProgressPost.setContent("Test progress content");
        testProgressPost.setProgressType(ProgressType.ACHIEVEMENT);
        testProgressPost.setVisibility(PostVisibility.PUBLIC);
        testProgressPost.setCreatedAt(LocalDateTime.now());

        // Test digest
        testDigest = new ProgressDigest();
        testDigest.setId(1L);
        testDigest.setUser(testUser);
        testDigest.setDigestType(DigestType.WEEKLY);
        testDigest.setStartDate(LocalDate.now().minusDays(7));
        testDigest.setEndDate(LocalDate.now());
        testDigest.setTotalPosts(10);
        testDigest.setAchievementsCount(5);
        testDigest.setSummary("Test weekly summary");
        testDigest.setCreatedAt(LocalDateTime.now());

        // Test meeting
        testMeeting = new OneOnOneMeeting();
        testMeeting.setId(1L);
        testMeeting.setEmployee(testUser);
        testMeeting.setManager(testUser);
        testMeeting.setScheduledDate(LocalDateTime.now());
        testMeeting.setAutoGeneratedAgenda("Test agenda");
        testMeeting.setStatus(MeetingStatus.SCHEDULED);
        testMeeting.setCreatedAt(LocalDateTime.now());
    }

    @Test
    void testExportProgressPostsToCsv() {
        // Arrange
        when(progressPostRepository.findByUserTenantIdAndCreatedAtBetweenOrderByCreatedAtDesc(
                anyLong(), any(), any())).thenReturn(Arrays.asList(testProgressPost));

        // Act
        byte[] csvData = exportService.exportProgressPostsToCsv(1L, LocalDate.now().minusDays(30), LocalDate.now());

        // Assert
        assertNotNull(csvData);
        assertTrue(csvData.length > 0);
        String csvContent = new String(csvData);
        assertTrue(csvContent.contains("Test User"));
        assertTrue(csvContent.contains("ACHIEVEMENT"));
        verify(progressPostRepository, times(1))
                .findByUserTenantIdAndCreatedAtBetweenOrderByCreatedAtDesc(anyLong(), any(), any());
    }

    @Test
    void testExportProgressPostsToExcel() throws Exception {
        // Arrange
        when(progressPostRepository.findByUserTenantIdAndCreatedAtBetweenOrderByCreatedAtDesc(
                anyLong(), any(), any())).thenReturn(Arrays.asList(testProgressPost));

        // Act
        byte[] excelData = exportService.exportProgressPostsToExcel(1L, LocalDate.now().minusDays(30), LocalDate.now());

        // Assert
        assertNotNull(excelData);
        assertTrue(excelData.length > 0);

        // Verify Excel structure
        try (Workbook workbook = new XSSFWorkbook(new ByteArrayInputStream(excelData))) {
            Sheet sheet = workbook.getSheetAt(0);
            assertNotNull(sheet);

            // Check header row
            Row headerRow = sheet.getRow(0);
            assertEquals("ID", headerRow.getCell(0).getStringCellValue());
            assertEquals("ユーザー", headerRow.getCell(1).getStringCellValue());

            // Check data row
            Row dataRow = sheet.getRow(1);
            assertEquals(1.0, dataRow.getCell(0).getNumericCellValue());
            assertEquals("Test User", dataRow.getCell(1).getStringCellValue());
        }

        verify(progressPostRepository, times(1))
                .findByUserTenantIdAndCreatedAtBetweenOrderByCreatedAtDesc(anyLong(), any(), any());
    }

    @Test
    void testExportDigestToCsv() {
        // Arrange
        when(progressDigestRepository.findById(1L)).thenReturn(Optional.of(testDigest));

        // Act
        byte[] csvData = exportService.exportDigestToCsv(1L);

        // Assert
        assertNotNull(csvData);
        assertTrue(csvData.length > 0);
        String csvContent = new String(csvData);
        assertTrue(csvContent.contains("WEEKLY"));
        assertTrue(csvContent.contains("10"));
        verify(progressDigestRepository, times(1)).findById(1L);
    }

    @Test
    void testExportDigestToMarkdown() {
        // Arrange
        testDigest.setKeyAchievements("Achievement 1\nAchievement 2");
        testDigest.setChallenges("Challenge 1");
        testDigest.setLearnings("Learning 1");
        testDigest.setNextSteps("Next step 1");
        when(progressDigestRepository.findById(1L)).thenReturn(Optional.of(testDigest));

        // Act
        byte[] markdownData = exportService.exportDigestToMarkdown(1L);

        // Assert
        assertNotNull(markdownData);
        assertTrue(markdownData.length > 0);
        String markdownContent = new String(markdownData);
        assertTrue(markdownContent.contains("# 進捗ダイジェスト"));
        assertTrue(markdownContent.contains("WEEKLY"));
        assertTrue(markdownContent.contains("Achievement 1"));
        verify(progressDigestRepository, times(1)).findById(1L);
    }

    @Test
    void testExportOneOnOneMeetingsToCsv() {
        // Arrange
        when(oneOnOneMeetingRepository.findByEmployeeTenantIdOrManagerTenantId(anyLong(), anyLong()))
                .thenReturn(Arrays.asList(testMeeting));

        // Act
        byte[] csvData = exportService.exportOneOnOneMeetingsToCsv(1L);

        // Assert
        assertNotNull(csvData);
        assertTrue(csvData.length > 0);
        String csvContent = new String(csvData);
        assertTrue(csvContent.contains("SCHEDULED"));
        verify(oneOnOneMeetingRepository, times(1))
                .findByEmployeeTenantIdOrManagerTenantId(anyLong(), anyLong());
    }

    @Test
    void testExportOneOnOneMeetingsToExcel() throws Exception {
        // Arrange
        when(oneOnOneMeetingRepository.findByEmployeeTenantIdOrManagerTenantId(anyLong(), anyLong()))
                .thenReturn(Arrays.asList(testMeeting));

        // Act
        byte[] excelData = exportService.exportOneOnOneMeetingsToExcel(1L);

        // Assert
        assertNotNull(excelData);
        assertTrue(excelData.length > 0);

        // Verify Excel structure
        try (Workbook workbook = new XSSFWorkbook(new ByteArrayInputStream(excelData))) {
            Sheet sheet = workbook.getSheetAt(0);
            assertNotNull(sheet);

            // Check header row
            Row headerRow = sheet.getRow(0);
            assertEquals("ID", headerRow.getCell(0).getStringCellValue());

            // Check data row
            Row dataRow = sheet.getRow(1);
            assertEquals(1.0, dataRow.getCell(0).getNumericCellValue());
        }

        verify(oneOnOneMeetingRepository, times(1))
                .findByEmployeeTenantIdOrManagerTenantId(anyLong(), anyLong());
    }

    @Test
    void testExportUsersToExcel() throws Exception {
        // Arrange
        List<User> users = Arrays.asList(testUser);
        when(userRepository.findByTenantId(1L)).thenReturn(users);

        // Act
        byte[] excelData = exportService.exportUsersToExcel(1L);

        // Assert
        assertNotNull(excelData);
        assertTrue(excelData.length > 0);

        // Verify Excel structure
        try (Workbook workbook = new XSSFWorkbook(new ByteArrayInputStream(excelData))) {
            Sheet sheet = workbook.getSheetAt(0);
            assertNotNull(sheet);

            // Check header row
            Row headerRow = sheet.getRow(0);
            assertEquals("ID", headerRow.getCell(0).getStringCellValue());
            assertEquals("ユーザー名", headerRow.getCell(1).getStringCellValue());

            // Check data row
            Row dataRow = sheet.getRow(1);
            assertEquals(1.0, dataRow.getCell(0).getNumericCellValue());
            assertEquals("testuser", dataRow.getCell(1).getStringCellValue());
        }

        verify(userRepository, times(1)).findByTenantId(1L);
    }

    @Test
    void testExportDigestToCsv_NotFound() {
        // Arrange
        when(progressDigestRepository.findById(999L)).thenReturn(Optional.empty());

        // Act & Assert
        assertThrows(RuntimeException.class, () -> {
            exportService.exportDigestToCsv(999L);
        });
    }

    @Test
    void testExportDigestToMarkdown_NotFound() {
        // Arrange
        when(progressDigestRepository.findById(999L)).thenReturn(Optional.empty());

        // Act & Assert
        assertThrows(RuntimeException.class, () -> {
            exportService.exportDigestToMarkdown(999L);
        });
    }
}
