package com.chatapp.service;

import com.chatapp.model.*;
import com.chatapp.repository.OneOnOneMeetingRepository;
import com.chatapp.repository.ProgressPostRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class OneOnOneMeetingServiceTest {

    @Mock
    private OneOnOneMeetingRepository meetingRepository;

    @Mock
    private ProgressPostRepository progressPostRepository;

    @InjectMocks
    private OneOnOneMeetingService meetingService;

    private User employee;
    private User manager;
    private Tenant testTenant;
    private OneOnOneMeeting testMeeting;
    private ProgressPost testPost;

    @BeforeEach
    void setUp() {
        // Test tenant
        testTenant = new Tenant();
        testTenant.setId(1L);
        testTenant.setName("Test Tenant");

        // Test employee
        employee = new User();
        employee.setId(1L);
        employee.setUsername("employee");
        employee.setDisplayName("Test Employee");
        employee.setTenantId(1L);

        // Test manager
        manager = new User();
        manager.setId(2L);
        manager.setUsername("manager");
        manager.setDisplayName("Test Manager");
        manager.setTenantId(1L);

        // Test progress post
        testPost = new ProgressPost();
        testPost.setId(1L);
        testPost.setAuthor(employee);
        testPost.setContent("Completed feature X");
        testPost.setBlockers("Need review from team");
        testPost.setLearnings("Learned new React patterns");
        testPost.setNextAction("Start feature Y");
        testPost.setCreatedAt(LocalDateTime.now());

        // Test meeting
        testMeeting = new OneOnOneMeeting();
        testMeeting.setId(1L);
        testMeeting.setEmployee(employee);
        testMeeting.setManager(manager);
        testMeeting.setTenant(testTenant);
        testMeeting.setScheduledAt(LocalDateTime.now().plusDays(1));
        testMeeting.setStatus(OneOnOneMeeting.MeetingStatus.SCHEDULED);
        testMeeting.setAutoGeneratedAgenda("Test agenda");
    }

    @Test
    void testCreateMeeting_Success() {
        // Arrange
        LocalDateTime scheduledAt = LocalDateTime.now().plusDays(1);
        List<ProgressPost> posts = Arrays.asList(testPost);

        when(progressPostRepository.findByAuthorAndCreatedAtBetween(any(), any(), any()))
                .thenReturn(posts);
        when(meetingRepository.save(any(OneOnOneMeeting.class))).thenReturn(testMeeting);

        // Act
        OneOnOneMeeting result = meetingService.createMeeting(employee, manager, testTenant, scheduledAt);

        // Assert
        assertNotNull(result);
        assertEquals(employee.getId(), result.getEmployee().getId());
        assertEquals(manager.getId(), result.getManager().getId());
        assertEquals(OneOnOneMeeting.MeetingStatus.SCHEDULED, result.getStatus());
        assertNotNull(result.getAutoGeneratedAgenda());
        verify(meetingRepository, times(1)).save(any(OneOnOneMeeting.class));
    }

    @Test
    void testGenerateAgenda_WithProgressPosts() {
        // Arrange
        LocalDateTime scheduledAt = LocalDateTime.now();
        List<ProgressPost> posts = Arrays.asList(testPost);

        when(progressPostRepository.findByAuthorAndCreatedAtBetween(any(), any(), any()))
                .thenReturn(posts);

        // Act
        String agenda = meetingService.generateAgenda(employee, testTenant, scheduledAt);

        // Assert
        assertNotNull(agenda);
        assertTrue(agenda.contains("1on1ミーティング アジェンダ"));
        assertTrue(agenda.contains("最近の達成事項"));
        assertTrue(agenda.contains("現在の課題"));
        assertTrue(agenda.contains("学び・気づき"));
        assertTrue(agenda.contains("Completed feature X"));
        assertTrue(agenda.contains("Need review from team"));
        assertTrue(agenda.contains("Learned new React patterns"));
        verify(progressPostRepository, times(1))
                .findByAuthorAndCreatedAtBetween(any(), any(), any());
    }

    @Test
    void testGenerateAgenda_WithNoPosts() {
        // Arrange
        LocalDateTime scheduledAt = LocalDateTime.now();
        List<ProgressPost> emptyPosts = Arrays.asList();

        when(progressPostRepository.findByAuthorAndCreatedAtBetween(any(), any(), any()))
                .thenReturn(emptyPosts);

        // Act
        String agenda = meetingService.generateAgenda(employee, testTenant, scheduledAt);

        // Assert
        assertNotNull(agenda);
        assertTrue(agenda.contains("1on1ミーティング アジェンダ"));
        assertTrue(agenda.contains("（記録なし）"));
        verify(progressPostRepository, times(1))
                .findByAuthorAndCreatedAtBetween(any(), any(), any());
    }

    @Test
    void testUpdateMeeting_Success() {
        // Arrange
        Long meetingId = 1L;
        String customAgenda = "Updated custom agenda";
        String discussionTopics = "Topic 1\nTopic 2";
        String actionItems = "Action 1\nAction 2";
        String notes = "Meeting notes";

        when(meetingRepository.findById(meetingId)).thenReturn(Optional.of(testMeeting));
        when(meetingRepository.save(any(OneOnOneMeeting.class))).thenReturn(testMeeting);

        // Act
        OneOnOneMeeting result = meetingService.updateMeeting(
                meetingId, customAgenda, discussionTopics, actionItems, notes);

        // Assert
        assertNotNull(result);
        verify(meetingRepository, times(1)).findById(meetingId);
        verify(meetingRepository, times(1)).save(any(OneOnOneMeeting.class));
    }

    @Test
    void testUpdateMeeting_NotFound() {
        // Arrange
        Long meetingId = 999L;
        when(meetingRepository.findById(meetingId)).thenReturn(Optional.empty());

        // Act & Assert
        assertThrows(RuntimeException.class, () -> {
            meetingService.updateMeeting(meetingId, "agenda", "topics", "actions", "notes");
        });
        verify(meetingRepository, times(1)).findById(meetingId);
        verify(meetingRepository, never()).save(any());
    }

    @Test
    void testCompleteMeeting_Success() {
        // Arrange
        Long meetingId = 1L;
        when(meetingRepository.findById(meetingId)).thenReturn(Optional.of(testMeeting));
        when(meetingRepository.save(any(OneOnOneMeeting.class))).thenReturn(testMeeting);

        // Act
        OneOnOneMeeting result = meetingService.completeMeeting(meetingId);

        // Assert
        assertNotNull(result);
        verify(meetingRepository, times(1)).findById(meetingId);
        verify(meetingRepository, times(1)).save(any(OneOnOneMeeting.class));
    }

    @Test
    void testGetEmployeeMeetings() {
        // Arrange
        Pageable pageable = PageRequest.of(0, 10);
        Page<OneOnOneMeeting> meetingPage = new PageImpl<>(Arrays.asList(testMeeting));

        when(meetingRepository.findByEmployeeAndTenantOrderByScheduledAtDesc(employee, testTenant, pageable))
                .thenReturn(meetingPage);

        // Act
        Page<OneOnOneMeeting> result = meetingService.getEmployeeMeetings(employee, testTenant, pageable);

        // Assert
        assertNotNull(result);
        assertEquals(1, result.getTotalElements());
        assertEquals(testMeeting.getId(), result.getContent().get(0).getId());
        verify(meetingRepository, times(1))
                .findByEmployeeAndTenantOrderByScheduledAtDesc(employee, testTenant, pageable);
    }

    @Test
    void testGetManagerMeetings() {
        // Arrange
        Pageable pageable = PageRequest.of(0, 10);
        Page<OneOnOneMeeting> meetingPage = new PageImpl<>(Arrays.asList(testMeeting));

        when(meetingRepository.findByManagerAndTenantOrderByScheduledAtDesc(manager, testTenant, pageable))
                .thenReturn(meetingPage);

        // Act
        Page<OneOnOneMeeting> result = meetingService.getManagerMeetings(manager, testTenant, pageable);

        // Assert
        assertNotNull(result);
        assertEquals(1, result.getTotalElements());
        verify(meetingRepository, times(1))
                .findByManagerAndTenantOrderByScheduledAtDesc(manager, testTenant, pageable);
    }

    @Test
    void testGetUpcomingMeetings() {
        // Arrange
        List<OneOnOneMeeting> upcomingMeetings = Arrays.asList(testMeeting);

        when(meetingRepository.findUpcomingMeetings(any(), any(), any()))
                .thenReturn(upcomingMeetings);

        // Act
        List<OneOnOneMeeting> result = meetingService.getUpcomingMeetings(employee, testTenant);

        // Assert
        assertNotNull(result);
        assertEquals(1, result.size());
        assertEquals(testMeeting.getId(), result.get(0).getId());
        verify(meetingRepository, times(1))
                .findUpcomingMeetings(any(), any(), any());
    }

    @Test
    void testGenerateAgenda_WithMultiplePosts() {
        // Arrange
        LocalDateTime scheduledAt = LocalDateTime.now();

        ProgressPost post2 = new ProgressPost();
        post2.setContent("Achievement 2");
        post2.setBlockers("Challenge 2");
        post2.setLearnings("Learning 2");

        List<ProgressPost> multiplePosts = Arrays.asList(testPost, post2);

        when(progressPostRepository.findByAuthorAndCreatedAtBetween(any(), any(), any()))
                .thenReturn(multiplePosts);

        // Act
        String agenda = meetingService.generateAgenda(employee, testTenant, scheduledAt);

        // Assert
        assertNotNull(agenda);
        assertTrue(agenda.contains("Achievement 2"));
        assertTrue(agenda.contains("Challenge 2"));
        assertTrue(agenda.contains("Learning 2"));
    }
}
